frutas/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static 
from django.conf import settings

app_name= 'frutas1'
urlpatterns = [
    path('', views.index, name='index'),
    path('frutas/<int:page>/', views.frutas_inicio, name='frutas'),
    path('estadisticas/', views.estadisticas_inicio, name='estadisticas'),
    path('usuario_detalle/<int:id_usuario>/', views.usuario_detalle, name='usuario_detalle'),
    path('proyecto/', views.proyecto, name='proyecto'),
    path('ranking/', views.ranking, name='ranking'),
    path('faltantes/', views.faltantes, name='faltantes'),
    path('versus/', views.versus, name='versus'),
    path('mostrar_usuarios/<int:page>/', views.mostrar_usuarios, name='mostrar_usuarios'),
    path('agregar_fruta/', views.agregar_fruta, name='agregar_fruta'),    
    path('administracion_frutas/', views.administracion_frutas, name='administracion_frutas'),   
    path('perfil_usuario/', views.perfil_usuario, name='perfil_usuario'),   
    path('actualizar_foto/', views.actualizar_foto, name='actualizar_foto'),   
     
] 

if settings.DEBUG:
    urlpatterns += static( settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frutas_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView
from django.conf.urls.static import static 
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('frutas.urls')),
    path('accounts/', include('allauth.urls')),
    path('logout', LogoutView.as_view(), name='logout' ),
    
]
if settings.DEBUG:
    urlpatterns += static( settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frutas/forms.py
from django import forms
from .models import Fruta
from django.db import models

class create_fruta(forms.ModelForm):
    class Meta:
        model = Fruta
        fields = ('nombre','descripcion','imagen'  )
        labels = {'imagen':'url de la imagen'}
        widgets={
            'nombre': forms.TextInput(
                attrs ={
                    'class':'form-control',
                    'required':''
                }
            ),
            'descripcion': forms.Textarea(
                attrs ={
                    'class':'form-control'
                }
            ),
            'imagen': forms.TextInput(
                attrs ={
                    'class':'form-control',
                    'placeholder':'https://images.unsplash.com/photo-1515778767554-42d4...',
                    'required':''
                }
            ),
        } 


class uploadImageForm(forms.Form):
    file = forms.FileField(required=False)
    

frutas/views.py
from typing import ContextManager
from django.core.exceptions import EmptyResultSet
from django.http.response import Http404
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from .models import Color, ComparacionFrutas, EstadisticaGenero, EstadisticaGlobal, Genero, LogFrutas, Region, Usuario , Fruta, PreferenciasFrutas, Sabor, EstadoFruta, LogUsuarios, UltimaPreferencia
from django.contrib.auth.models import User
import math
import random
from django.urls import reverse
from .forms import create_fruta
from django.utils import timezone
import pymysql
from .forms import uploadImageForm
import os
from dotenv import load_dotenv
load_dotenv()


# Create your views here.
def obtener_avatar(id_usuario):
    conn = pymysql.connect(host='127.0.0.1', user=os.getenv('db_user'), password=os.getenv('db_pass'), database=os.getenv('db_name'), charset='utf8')
    cur = conn.cursor()
    #dato = cur.callproc("obtener_avatar_provider", (id_usuario,))
    sentencia_sql = "SELECT obtener_avatar_provider(%s)",(id_usuario)
    cur.execute(
        "SELECT obtener_avatar_provider(%s)",(id_usuario)
        )
    dato = cur.fetchone()    
    conn.close()      
    return dato[0]

def actualizar_foto(request):
    conn = pymysql.connect(host='127.0.0.1', user=os.getenv('db_user'), password=os.getenv('db_pass'), database=os.getenv('db_name'), charset='utf8')
    cur = conn.cursor()
    cur.callproc("actualizar_foto", (request.user.id,))
    conn.commit()
    conn.close()
    #return render(request,'frutas/perfil_usuario.html')    
    return perfil_usuario(request)


def perfil_usuario(request):
    if request.method == 'POST':  
        if(request.POST.get('accion')=='eliminar_usuario' ):
                usuario_obj2 = Usuario.objects.get(id = request.POST.get('id_usuario') )
                #borrar log usuario
                log_usuario_obj= LogUsuarios.objects.filter(usuario_emisor=usuario_obj2)
                for lu in log_usuario_obj:
                    lu.delete()  

                #borrar comparaciones 
                comparaciones_usuario_obj = ComparacionFrutas.objects.filter(usuario=usuario_obj2)
                for cu in comparaciones_usuario_obj:
                    cu.delete()

                #borrar ultima preferencia
                ultimapref_usuario_obj = UltimaPreferencia.objects.filter(usuario=usuario_obj2)
                for up in ultimapref_usuario_obj:
                    up.delete() 
                
                #borrar preferencias usuarios 
                pref_usuario_obj = PreferenciasFrutas.objects.filter(usuario=usuario_obj2)
                for pu in pref_usuario_obj:
                    pu.delete() 

                #borrar usuario
                usuario_obj2.delete()  
                #cerrar sesion 
                #eliminar cuenta
                #redirigir a inicio
                return HttpResponseRedirect('/frutas/1/')            
                #return HttpResponseRedirect(reverse{% url 'logout' %}"
        else:
            usuario_obj = Usuario.objects.get(id=request.user.id)
            if (request.POST.get('region') != ''):
                region_obj = Region.objects.get(id = request.POST.get('region'))
                usuario_obj.region = region_obj
            if (request.POST.get('genero') != ''):
                genero_obj = Genero.objects.get(id = request.POST.get('genero'))
                usuario_obj.genero = genero_obj 
            #form = uploadImageForm(request.POST, request.FILES)
            if (request.FILES.get('file')==None):
                usuario_obj.imagen_avatar = (request.POST.get('exampleRadios'))
            else:
                def handle_upload_file(f):
                    with open('media/' + str(request.FILES['file']) , 'wb+') as destination:
                        for chunk in f.chunks():
                            destination.write(chunk)   
                archivo_path= '/media/'+  str(request.FILES.get('file'))
                handle_upload_file(request.FILES['file'])
                usuario_obj.imagen_avatar = archivo_path                           
            usuario_obj.nombre= request.POST.get('nombre')
            usuario_obj.save()
            
        
    avatar_provider = str(obtener_avatar(request.user.id))
    regiones_list = Region.objects.all().order_by('nombre')
    genero_list = Genero.objects.all()
    usuario_object = Usuario.objects.get(id=request.user.id)
    por_completar_list =list()
    if usuario_object.genero == None:
        por_completar_list.append('Indicar genero')
    context = {'regiones_list':regiones_list, 'genero_list':genero_list, 'por_completar_list':por_completar_list, 'uploadImageForm':uploadImageForm, 'avatar_provider':avatar_provider}
    return render(request,'frutas/agregar_imagen.html', context)   
    

def index(request):
    #return render(request,'frutas/base.html')
    return render(request,'frutas/inicio.html')


def agregar_fruta(request):
    if request.method == 'POST':
        nombre_get= request.POST.get('nombre')
        descripcion_get=request.POST.get('descripcion')
        imagen_get=request.POST.get('imagen')
        color_object =  Color.objects.get(id=request.POST.get('color'))   
        sabor_object = Sabor.objects.get(id=request.POST.get('sabor'))   
        estado_fruta_object= EstadoFruta.objects.get(nombre__icontains='enviado')
        Fruta.objects.create(nombre =nombre_get , color_principal =color_object , sabor= sabor_object, estado_fruta=estado_fruta_object , descripcion =descripcion_get ,imagen=imagen_get)
        form = create_fruta(request.POST)
        if form.is_valid():
            return HttpResponseRedirect('/frutas/1/')
    else:
        form = create_fruta()
        list_sabores = Sabor.objects.all()
        list_colores = Color.objects.all()
        context= {'list_sabores':list_sabores, 'list_colores':list_colores, 'form':form}
    return render(request,'frutas/agregar_fruta.html', context)


def ranking(request):
    if request.method == 'POST':     
        if request.POST.get('accion')== 'eliminar_ranking' :               
            usuario_obj2 = Usuario.objects.get(id = request.POST.get('id_usuario') )

            #borrar comparaciones 
            comparaciones_usuario_obj = ComparacionFrutas.objects.filter(usuario=usuario_obj2)
            for cu in comparaciones_usuario_obj:
                cu.delete()

            #borrar ultima preferencia
            ultimapref_usuario_obj = UltimaPreferencia.objects.filter(usuario=usuario_obj2)
            for up in ultimapref_usuario_obj:
                up.delete() 

            #borrar preferencias usuarios 
            pref_usuario_obj = PreferenciasFrutas.objects.filter(usuario=usuario_obj2)
            for pu in pref_usuario_obj:
                pu.delete() 
    return render(request,'frutas/ranking.html')


def faltantes(request):
    if request.method == 'POST':
        id_fruta_aux =request.POST.get('id_fruta')
        id_user_aux = request.POST.get('id_usuario')
        #revisar lo de abajo
        pref_object = PreferenciasFrutas.objects.get(id=id_fruta_aux, usuario=id_user_aux)
        max_ranking = PreferenciasFrutas.objects.filter(usuario=id_user_aux).exclude(ranking_valor__isnull=True).count()
        pref_object.ranking_valor = max_ranking+1
        pref_object.save()

        #ACTUALIZAR ULTIMA PREFERENCIA
        conn = pymysql.connect(host='127.0.0.1', user=os.getenv('db_user'), password=os.getenv('db_pass'), database=os.getenv('db_name'), charset='utf8')
        cur = conn.cursor()
        cur.callproc("actualizar_ultima_preferencia", (request.user.id,))
        conn.commit()
        conn.close()
        return HttpResponseRedirect('/faltantes/')
    else:
        form = create_fruta()
        list_sabores = Sabor.objects.all()
        list_colores = Color.objects.all()
        context= {'list_sabores':list_sabores, 'list_colores':list_colores, 'form':form}

    



    return render(request,'frutas/faltantes.html')




def versus(request):
    if request.method == 'POST':
        accion_aux =request.POST.get('accion')
        id_user_aux = request.POST.get('id_usuario')
        usuario_obj = Usuario.objects.get(id=id_user_aux)

        if accion_aux=='preferencia' :
            fruta1_obj= Fruta.objects.get(id=request.POST.get('fruta1'))
            fruta2_obj= Fruta.objects.get(id=request.POST.get('fruta2'))
            elecccion_obj = Fruta.objects.get(id=request.POST.get('eleccion'))
            ComparacionFrutas.objects.create(usuario=usuario_obj,fruta1=fruta1_obj, fruta2=fruta2_obj, eleccion=elecccion_obj, fecha_comparacion= timezone.now())

        if accion_aux=='sinprobar' :            
            fruta3_aux =request.POST.get('id_fruta')
            fruta3_obj = Fruta.objects.get(id=fruta3_aux)
            pref_bool = PreferenciasFrutas.objects.filter(usuario=usuario_obj, fruta= fruta3_aux).exists()

            if pref_bool==True:
                fruta3_obj = PreferenciasFrutas.objects.get(usuario=usuario_obj, fruta= fruta3_aux)
                fruta3_obj.ranking_valor = None
                fruta3_obj.save()
            else:
                PreferenciasFrutas.objects.create(usuario=usuario_obj, fruta= fruta3_obj, ranking_valor= None)

    user_id= request.user.id
    #ver si existen comparaciones por realizar 
    estado_object = EstadoFruta.objects.get(nombre__icontains='aprobado')
    list_frutas_validas= Fruta.objects.all().filter(estado_fruta=estado_object)
        #verificar en esta lista que no hayan valores que el usuario no haya probado
    for f in list_frutas_validas:
        pref_bool = PreferenciasFrutas.objects.filter(usuario=user_id, fruta=f.id).exists()
        if(pref_bool==True):
            pref_object = PreferenciasFrutas.objects.get(usuario=user_id, fruta=f.id)
            if(pref_object.ranking_valor == None ):
                list_frutas_validas=list_frutas_validas.exclude(id=f.id)

frutas/templates/frutas/administracion_frutas.html
{% extends "frutas/base.html" %}

{% block contenido %}
        <style> 
            .card:hover{
                box-shadow: 0px 0px 5px 1px black;
            }

        </style>
    <h1 class="row justify-content-md-center">Solicitudes de frutas</h1>
    
    {% if user.is_superuser%}
        {% if frutas %}
            <div class="row ">
                {% for f in frutas %}
                    <div class="card  col-sm-12 col-md-6 col-lg-3 my-2  g-4"  >
                        <img src="{{f.imagen}}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title">{{f.nombre|capfirst}}</h5>
                            <p class="card-text">{{f.descripcion}}</p>
                            </div>
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item">Sabor <span class="badge rounded-pill bg-info text-dark">{{f.sabor}}</li>
                                <li class="list-group-item">Color principal <span class="badge rounded-pill bg-info text-dark">{{f.color_principal}}</span> </li>

                                <div class="row">
                                    <form class="my-4 col-4 post-form" action="" method="POST">
                                        {% csrf_token %}   
                                        <input type="hidden" id="custId" name="id_fruta" value="{{f.id}}"> 
                                        <input type="hidden" id="custId" name="accion" value="publicar">                                                      
                                        <button type="submit" class="btn btn-warning">Publicar</button>
                                    </form> 
    
                                    <form class="my-4 col-4 post-form" action="" method="POST">
                                        {% csrf_token %}   
                                        <input type="hidden" id="custId" name="id_fruta" value="{{f.id}}">  
                                        <input type="hidden" id="custId" name="accion" value="eliminar">                                                      
                                        <button type="submit" class="btn btn-danger">Eliminar</button>
                                    </form> 
                                </div>
                            </ul>
                        </div>
                {% endfor %}
                
            </div>
        {% else %}
            <p>No fruits are available.</p>
        {% endif %} 
    {% else %}
            usted no tiene permiso para ver esta seccion
    {% endif %}
    


{% endblock %}

frutas/templates/frutas/faltantes.html
{% extends "frutas/base.html" %}

{% block contenido %}
    <style> 
        .list-group-item:hover{
            box-shadow: 0px 0px 5px 1px black;
        }

    </style>
    {% if user.is_authenticated %}
        <h1 class="row justify-content-md-center">Mi lista de no probados</h1>
        {% if faltantes  %}

                <ul class="list-group my-4 list-group">
                    {% for e in faltantes%}
                    <li class="list-group-item my-1 d-flex justify-content-between align-items-start">
                        <div class="ms-2 me-auto">
                            <div class="fw-bold">{{e.fruta|capfirst}}</div>
                        </div>
                        <form post-form" action="" method="POST">
                            {% csrf_token %}   
                            <input type="hidden" id="custId" name="id_fruta" value="{{e.id}}"> 
                            <input type="hidden" id="custId" name="id_usuario" value="{{usuario_conectado.id}}"> 
                            <button type="submit" class="btn btn-outline-danger">quitar</button>
                        </form>                       
                    </li>
                    {% endfor %}
                </ul>
                
<!-- 
            <ul class="list-group my-4 ">    
                {% for e in faltantes%}
                    <div class="row">
                        
                            <li class="list-group-item">
                                <div class="col-8">
                                    <input class="form-check-input me-1" type="checkbox" value="{{e.fruta}}" aria-label="...">{{e.fruta}}
                                </div>

                                <div class="col-4">
                                    <a href="">quitar</a>
                                </div>
                            </li>  
                        
                        
                    </div>
                {% endfor %}
            </ul>
            <p >las frutas seleccionadas se eliminaran de la lista</p>
            <button type="button" class="btn btn-warning mb-4">Guardar cambios</button>
 -->

        {% else %}
            Parece que has probado todas las frutas que hay disponibles<br>

            <ol class="list-group list-group my-4">            
                <li class="list-group-item"> agrega frutas nuevas <a href="{% url 'frutas1:agregar_fruta' %}"><span class="badge bg-info text-dark">aca</span> </a> </li>
            </ol>

        {% endif %}
    {% else %}
        debe estar conectado para ver esta opcion
    {% endif %}

{% endblock %}

frutas/templates/frutas/frutas.html
{% extends "frutas/base.html" %}

{% block contenido %}
    <h1 class="row justify-content-md-center">Echale un vistazo a las frutas</h1>
    
    {% if frutas %}
        <div class="row ">
            {% for f in frutas %}
                <div class="card  col-sm-12 col-md-6 col-lg-3 my-2  g-4"  >
                    <img src="{{f.imagen}}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">{{f.nombre|capfirst}}</h5>
                        <p class="card-text">{{f.descripcion}}</p>
                        </div>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">Sabor <span class="badge rounded-pill bg-info text-dark">{{f.sabor}}</li>
                            <li class="list-group-item">Color principal <span class="badge rounded-pill bg-info text-dark">{{f.color_principal}}</span> </li>
                        </ul>
                    </div>
            {% endfor %}
        </div>
    {% else %}
        <p>No fruits are available.</p>
    {% endif %} 
    {% if user.is_authenticated %}   
        <a href="{% url 'frutas1:agregar_fruta' %}"><button type="button" class="btn btn-outline-secondary">Agrega frutas nuevas </button></a>
    {% endif %}
    <div class="row my-4">
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
                {% if page|stringformat:"s" == '1' %}
                    <li class="page-item disabled "><a class="page-link" href="{% url 'frutas1:frutas' prev_pag %}" tabindex="-1" >Anterior</a></li>
                {% else %}
                    <li class="page-item "><a class="page-link" href="{% url 'frutas1:frutas' prev_pag %}" tabindex="-1" >Anterior</a></li>
                {% endif %}               
                {% for i in list_num_paginas %}        
                        <li class="page-item  {% if page|stringformat:"s" == i|stringformat:"s"  %} active {% endif %}   "><a class="page-link" href="{% url 'frutas1:frutas' i %}">{{i}}</a></li>                                  
                {% endfor %}  
                
                {% if page == num_paginas %}
                    <li class="page-item disabled"><a class="page-link" href="{% url 'frutas1:frutas' next_pag %}">Siguiente</a></li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="{% url 'frutas1:frutas' next_pag %}">Siguiente</a></li>
                {% endif %}                                
            </ul>
        </nav>
    </div>


{% endblock %}

frutas/templates/frutas/mostrar_usuarios.html
{% extends "frutas/base.html" %}

{% block contenido %}
    <style> 
        .card:hover{
            box-shadow: 0px 0px 5px 1px black;
        }

    </style>



    <h1 class="row justify-content-md-center">Ultimos usuarios creados</h1>
    {% if lista_usuarios %} 
    <div class="row justify-content-md-center mb-4">

        {% for u in lista_usuarios %}
            <!-- <div class="card col-sm-12 col-md-3 my-2 mx-1"> -->
                <div class="card my-2 mx-2"  style="width: 10rem;" >
                    <a href="{% url 'frutas1:usuario_detalle' u.id %}">
                        {% if u.imagen_avatar %}
                            <img src="{{u.imagen_avatar}}" class="card-img-top" alt="..." width="50">
                        {% else %}
                            <img src="https://i.pinimg.com/236x/21/09/47/21094753857210805aa234b3ade8cc1d.jpg" class="card-img-top" alt="..." width="50">                        
                        {% endif %} 
                        
                    </a>

                    <div class="card-body">
                        <h5 class="card-title">{{u.nombre|capfirst}}</h5>
                    </div>
                    <div class="card-footer">
                        <small class="text-muted">se unio en : {{u.fecha_creacion}}</small>
                    </div>                                        
                </div>           
        {% endfor %}        
    </div>

    <div class="row">
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
                {% if page|stringformat:"s" == '1' %}
                    <li class="page-item disabled "><a class="page-link" href="{% url 'frutas1:mostrar_usuarios' prev_pag %}" tabindex="-1" >  Anterior  </a></li>
                {% else %}
                    <li class="page-item "><a class="page-link" href="{% url 'frutas1:mostrar_usuarios' prev_pag %}" tabindex="-1" > Anterior </a></li>
                {% endif %}               
                {% for i in list_num_paginas %}        
                        <li class="page-item {% if page|stringformat:"s" == i|stringformat:"s"  %} active {% endif %}    "><a class="page-link" href="{% url 'frutas1:mostrar_usuarios' i %}">{{i}}</a></li>                                  
                {% endfor %}  
                
                {% if page == num_paginas %}
                    <li class="page-item disabled"><a class="page-link" href="{% url 'frutas1:mostrar_usuarios' next_pag %}"> Siguiente </a></li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="{% url 'frutas1:mostrar_usuarios' next_pag %}">  Siguiente </a></li>
                {% endif %}
                
                
            </ul>
        </nav>
    </div>


    {% else %}
        <p>No user are available.</p>
    {% endif %} 

{% endblock %}

frutas/templates/frutas/perfil_usuario.html
{% extends "frutas/base.html" %}

{% block contenido %}
<h1 class="row justify-content-md-center my-2">Perfil de usuario</h1>

    


    {% if por_completar_list %}
        <div class="alert alert-danger" role="alert">
            <span>porfavor completa los siguientes datos faltantes</span>
            <ul>
                {%for i in por_completar_list %}
                    <li>{{i}}</li>
                {% endfor %}
            </ul>
        </div>
        
        
    {% endif %}
    {% if usuario_conectado %}
        <form class="my-4 post-form" action="" method="POST">
            {% csrf_token %}
            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Nombre</label>
                <input name="nombre" type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp"  value="{{usuario_conectado.nombre}}">                
            </div>

            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Foto perfil  <a href="{% url 'frutas1:actualizar_foto' %}"><span class="badge rounded-pill  bg-dark">actualizar foto </span></a> </label>
                <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp"  value="{{usuario_conectado.imagen_avatar}}" disabled>                
            </div>

            <select name="genero" class="form-select form-control form-select-md mb-3" aria-label=".form-select-lg example" >
                {% if usuario_conectado.genero %}
                    <option value="{{usuario_conectado.genero.id}}" selected>{{usuario_conectado.genero}} </option>
                {% else %}
                    <option value="" selected>Seleccione Genero </option>
                {% endif %}
                {% for s in genero_list %}   
                    {% if s != usuario_conectado.genero %} 
                        <option value="{{s.id}}">{{s.titulo}}</option> 
                    {% endif %}
                {% endfor %}
                
            </select>

            <select name="region" class="form-select form-control form-select-md mb-3" aria-label=".form-select-lg example" >
                {% if usuario_conectado.region %}
                    <option value="{{usuario_conectado.region.id}}" selected>{{usuario_conectado.region}} </option>
                {% else %}
                    <option value="" selected>Seleccione Region </option>
                {% endif %}
                {% for s in regiones_list %}    
                    {% if s != usuario_conectado.region %} 
                        <option value="{{s.id}}">{{s.nombre}}</option> 
                    {% endif %}            
                {% endfor %}
            </select>

            <button type="submit" class="btn btn-warning">Guardar</button>
            <!-- Button trigger modal -->
            <button type="button"  class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">
                Borrar cuenta
            </button>
        </form> 

    {% else %}
        no hay usuario conectado
    {% endif %}


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Borrar cuenta</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">      
        Se borraran todos los datos de la cuenta para siempre, esta accion no se puede deshacer.<br> ¿desea continuar?
      </div>
      <div class="modal-footer">
             <form class="my-4 post-form" action="" method="POST">
                {% csrf_token %}                  
                <input type="hidden"  name="id_usuario" value="{{usuario_conectado.id}}">  
                <input type="hidden"  name="accion" value="eliminar_usuario">
               
                    <button type="submit" class="btn btn-outline-danger">Borrar cuenta</button>             
            </form>        
             <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
      </div>
    </div>
  </div>
</div>





{% endblock %}

frutas/templates/frutas/ranking.html
{% extends "frutas/base.html" %}

{% block contenido %}
    {% if user.is_authenticated %}
        <h1 class="row justify-content-md-center">Mi ranking</h1>
        {% if ranking  %}

            <ol class="list-group list-group my-4">
                {% for e in ranking%}
                <li class="list-group-item">  <span class="badge rounded-pill bg-primary">{{e.ranking_valor}} °</span>  {{e.fruta|capfirst}}</li>           
                {% endfor %}
                <li class="list-group-item"> sigue actualizando tu ranking en  <a href="{% url 'frutas1:versus' %}"><span class="badge bg-info text-dark">Versus</span></a> 
                    o agrega frutas nuevas <a href="{% url 'frutas1:agregar_fruta' %}"><span class="badge bg-info text-dark">aca</span> </a> 
                </li>

                <li class="list-group-item"> 
                    <button type="button"  class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">
                        Reiniciar ranking
                    </button>                    
                </li>
                
            </ol>
           


        {% else %}
            no hay elementos que mostrar
            <ol class="list-group list-group my-4">            
                <li class="list-group-item"> actualiza tu ranking en     <a href="{% url 'frutas1:versus' %}"><span class="badge bg-info text-dark">Versus</span></a> 
                    o agrega frutas nuevas <a href="{% url 'frutas1:agregar_fruta' %}"><span class="badge bg-info text-dark">aca</span> </a> 
                </li>
            </ol>

        {% endif %}
    {% else %}
            debe estar conectado para ver esta opcion
    {% endif %}


    <!-- Modal -->
 <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Borrar registro de preferencias</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">      
          Se borraran todos las comparaciones y preferencias de frutas, esta accion no se puede deshacer.<br> ¿desea continuar?
        </div>
        <div class="modal-footer">
               <form class="my-4 post-form" action="" method="POST">
                  {% csrf_token %}                  
                  <input type="hidden"  name="id_usuario" value="{{usuario_conectado.id}}">  
                  <input type="hidden"  name="accion" value="eliminar_ranking">
                 
                      <button type="submit" class="btn btn-outline-danger">Borrar preferencias</button>             
              </form>        
               <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
        </div>
      </div>
    </div>
  </div>

{% endblock %}